/**
 * Bundled ISO 4217 active currency list (~170 entries).
 * Source: ISO 4217 maintenance agency (wikipedia.org/wiki/ISO_4217 active codes table).
 * Obsolete codes (DEM, FRF, XEU, etc.) are excluded.
 * Updates to this list ship with a code release (research.md R3).
 */

export type Currency = {
  /** ISO 4217 alpha-3 uppercase code (e.g., "USD") */
  code: string
  /** English name (e.g., "United States Dollar") */
  name: string
  /**
   * ISO 4217 default fraction digits (e.g., 2 for USD, 0 for JPY, 3 for BHD).
   * Used for currency-aware decimal-place validation (FR-006).
   */
  decimals: 0 | 1 | 2 | 3 | 4
  /** Display symbol (e.g., "$", "€"). Falls back to the code when no widely-recognized symbol exists. */
  symbol: string
}

export const CURRENCIES: readonly Currency[] = [
  { code: "AED", name: "UAE Dirham", decimals: 2, symbol: "د.إ" },
  { code: "AFN", name: "Afghan Afghani", decimals: 2, symbol: "؋" },
  { code: "ALL", name: "Albanian Lek", decimals: 2, symbol: "L" },
  { code: "AMD", name: "Armenian Dram", decimals: 2, symbol: "֏" },
  { code: "ANG", name: "Netherlands Antillean Guilder", decimals: 2, symbol: "ƒ" },
  { code: "AOA", name: "Angolan Kwanza", decimals: 2, symbol: "Kz" },
  { code: "ARS", name: "Argentine Peso", decimals: 2, symbol: "$" },
  { code: "AUD", name: "Australian Dollar", decimals: 2, symbol: "A$" },
  { code: "AWG", name: "Aruban Florin", decimals: 2, symbol: "ƒ" },
  { code: "AZN", name: "Azerbaijani Manat", decimals: 2, symbol: "₼" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", decimals: 2, symbol: "KM" },
  { code: "BBD", name: "Barbadian Dollar", decimals: 2, symbol: "Bds$" },
  { code: "BDT", name: "Bangladeshi Taka", decimals: 2, symbol: "৳" },
  { code: "BGN", name: "Bulgarian Lev", decimals: 2, symbol: "лв" },
  { code: "BHD", name: "Bahraini Dinar", decimals: 3, symbol: "BD" },
  { code: "BIF", name: "Burundian Franc", decimals: 0, symbol: "Fr" },
  { code: "BMD", name: "Bermudian Dollar", decimals: 2, symbol: "$" },
  { code: "BND", name: "Brunei Dollar", decimals: 2, symbol: "B$" },
  { code: "BOB", name: "Bolivian Boliviano", decimals: 2, symbol: "Bs." },
  { code: "BOV", name: "Bolivian Mvdol", decimals: 2, symbol: "BOV" },
  { code: "BRL", name: "Brazilian Real", decimals: 2, symbol: "R$" },
  { code: "BSD", name: "Bahamian Dollar", decimals: 2, symbol: "B$" },
  { code: "BTN", name: "Bhutanese Ngultrum", decimals: 2, symbol: "Nu" },
  { code: "BWP", name: "Botswana Pula", decimals: 2, symbol: "P" },
  { code: "BYN", name: "Belarusian Ruble", decimals: 2, symbol: "Br" },
  { code: "BZD", name: "Belize Dollar", decimals: 2, symbol: "BZ$" },
  { code: "CAD", name: "Canadian Dollar", decimals: 2, symbol: "CA$" },
  { code: "CDF", name: "Congolese Franc", decimals: 2, symbol: "Fr" },
  { code: "CHE", name: "WIR Euro", decimals: 2, symbol: "CHE" },
  { code: "CHF", name: "Swiss Franc", decimals: 2, symbol: "Fr" },
  { code: "CHW", name: "WIR Franc", decimals: 2, symbol: "CHW" },
  { code: "CLF", name: "Chilean Unit of Account (UF)", decimals: 4, symbol: "CLF" },
  { code: "CLP", name: "Chilean Peso", decimals: 0, symbol: "$" },
  { code: "CNY", name: "Chinese Yuan", decimals: 2, symbol: "¥" },
  { code: "COP", name: "Colombian Peso", decimals: 2, symbol: "$" },
  { code: "COU", name: "Colombian Real Value Unit", decimals: 2, symbol: "COU" },
  { code: "CRC", name: "Costa Rican Colón", decimals: 2, symbol: "₡" },
  { code: "CUP", name: "Cuban Peso", decimals: 2, symbol: "$" },
  { code: "CVE", name: "Cape Verdean Escudo", decimals: 2, symbol: "$" },
  { code: "CZK", name: "Czech Koruna", decimals: 2, symbol: "Kč" },
  { code: "DJF", name: "Djiboutian Franc", decimals: 0, symbol: "Fr" },
  { code: "DKK", name: "Danish Krone", decimals: 2, symbol: "kr" },
  { code: "DOP", name: "Dominican Peso", decimals: 2, symbol: "RD$" },
  { code: "DZD", name: "Algerian Dinar", decimals: 2, symbol: "دج" },
  { code: "EGP", name: "Egyptian Pound", decimals: 2, symbol: "£" },
  { code: "ERN", name: "Eritrean Nakfa", decimals: 2, symbol: "Nfk" },
  { code: "ETB", name: "Ethiopian Birr", decimals: 2, symbol: "Br" },
  { code: "EUR", name: "Euro", decimals: 2, symbol: "€" },
  { code: "FJD", name: "Fijian Dollar", decimals: 2, symbol: "FJ$" },
  { code: "FKP", name: "Falkland Islands Pound", decimals: 2, symbol: "£" },
  { code: "GBP", name: "British Pound Sterling", decimals: 2, symbol: "£" },
  { code: "GEL", name: "Georgian Lari", decimals: 2, symbol: "₾" },
  { code: "GHS", name: "Ghanaian Cedi", decimals: 2, symbol: "₵" },
  { code: "GIP", name: "Gibraltar Pound", decimals: 2, symbol: "£" },
  { code: "GMD", name: "Gambian Dalasi", decimals: 2, symbol: "D" },
  { code: "GNF", name: "Guinean Franc", decimals: 0, symbol: "Fr" },
  { code: "GTQ", name: "Guatemalan Quetzal", decimals: 2, symbol: "Q" },
  { code: "GYD", name: "Guyanese Dollar", decimals: 2, symbol: "G$" },
  { code: "HKD", name: "Hong Kong Dollar", decimals: 2, symbol: "HK$" },
  { code: "HNL", name: "Honduran Lempira", decimals: 2, symbol: "L" },
  { code: "HTG", name: "Haitian Gourde", decimals: 2, symbol: "G" },
  { code: "HUF", name: "Hungarian Forint", decimals: 2, symbol: "Ft" },
  { code: "IDR", name: "Indonesian Rupiah", decimals: 2, symbol: "Rp" },
  { code: "ILS", name: "Israeli New Shekel", decimals: 2, symbol: "₪" },
  { code: "INR", name: "Indian Rupee", decimals: 2, symbol: "₹" },
  { code: "IQD", name: "Iraqi Dinar", decimals: 3, symbol: "ع.د" },
  { code: "IRR", name: "Iranian Rial", decimals: 2, symbol: "﷼" },
  { code: "ISK", name: "Icelandic Króna", decimals: 0, symbol: "kr" },
  { code: "JMD", name: "Jamaican Dollar", decimals: 2, symbol: "J$" },
  { code: "JOD", name: "Jordanian Dinar", decimals: 3, symbol: "JD" },
  { code: "JPY", name: "Japanese Yen", decimals: 0, symbol: "¥" },
  { code: "KES", name: "Kenyan Shilling", decimals: 2, symbol: "Ksh" },
  { code: "KGS", name: "Kyrgyzstani Som", decimals: 2, symbol: "с" },
  { code: "KHR", name: "Cambodian Riel", decimals: 2, symbol: "៛" },
  { code: "KMF", name: "Comorian Franc", decimals: 0, symbol: "Fr" },
  { code: "KPW", name: "North Korean Won", decimals: 2, symbol: "₩" },
  { code: "KRW", name: "South Korean Won", decimals: 0, symbol: "₩" },
  { code: "KWD", name: "Kuwaiti Dinar", decimals: 3, symbol: "KD" },
  { code: "KYD", name: "Cayman Islands Dollar", decimals: 2, symbol: "CI$" },
  { code: "KZT", name: "Kazakhstani Tenge", decimals: 2, symbol: "₸" },
  { code: "LAK", name: "Lao Kip", decimals: 2, symbol: "₭" },
  { code: "LBP", name: "Lebanese Pound", decimals: 2, symbol: "ل.ل" },
  { code: "LKR", name: "Sri Lankan Rupee", decimals: 2, symbol: "Rs" },
  { code: "LRD", name: "Liberian Dollar", decimals: 2, symbol: "L$" },
  { code: "LSL", name: "Lesotho Loti", decimals: 2, symbol: "M" },
  { code: "LYD", name: "Libyan Dinar", decimals: 3, symbol: "LD" },
  { code: "MAD", name: "Moroccan Dirham", decimals: 2, symbol: "MAD" },
  { code: "MDL", name: "Moldovan Leu", decimals: 2, symbol: "L" },
  { code: "MGA", name: "Malagasy Ariary", decimals: 2, symbol: "Ar" },
  { code: "MKD", name: "Macedonian Denar", decimals: 2, symbol: "den" },
  { code: "MMK", name: "Myanmar Kyat", decimals: 2, symbol: "K" },
  { code: "MNT", name: "Mongolian Tögrög", decimals: 2, symbol: "₮" },
  { code: "MOP", name: "Macanese Pataca", decimals: 2, symbol: "P" },
  { code: "MRU", name: "Mauritanian Ouguiya", decimals: 2, symbol: "UM" },
  { code: "MUR", name: "Mauritian Rupee", decimals: 2, symbol: "Rs" },
  { code: "MVR", name: "Maldivian Rufiyaa", decimals: 2, symbol: "Rf" },
  { code: "MWK", name: "Malawian Kwacha", decimals: 2, symbol: "MK" },
  { code: "MXN", name: "Mexican Peso", decimals: 2, symbol: "MX$" },
  { code: "MXV", name: "Mexican Investment Unit", decimals: 2, symbol: "MXV" },
  { code: "MYR", name: "Malaysian Ringgit", decimals: 2, symbol: "RM" },
  { code: "MZN", name: "Mozambican Metical", decimals: 2, symbol: "MT" },
  { code: "NAD", name: "Namibian Dollar", decimals: 2, symbol: "N$" },
  { code: "NGN", name: "Nigerian Naira", decimals: 2, symbol: "₦" },
  { code: "NIO", name: "Nicaraguan Córdoba", decimals: 2, symbol: "C$" },
  { code: "NOK", name: "Norwegian Krone", decimals: 2, symbol: "kr" },
  { code: "NPR", name: "Nepalese Rupee", decimals: 2, symbol: "Rs" },
  { code: "NZD", name: "New Zealand Dollar", decimals: 2, symbol: "NZ$" },
  { code: "OMR", name: "Omani Rial", decimals: 3, symbol: "ر.ع." },
  { code: "PAB", name: "Panamanian Balboa", decimals: 2, symbol: "B/." },
  { code: "PEN", name: "Peruvian Sol", decimals: 2, symbol: "S/" },
  { code: "PGK", name: "Papua New Guinean Kina", decimals: 2, symbol: "K" },
  { code: "PHP", name: "Philippine Peso", decimals: 2, symbol: "₱" },
  { code: "PKR", name: "Pakistani Rupee", decimals: 2, symbol: "Rs" },
  { code: "PLN", name: "Polish Złoty", decimals: 2, symbol: "zł" },
  { code: "PYG", name: "Paraguayan Guaraní", decimals: 0, symbol: "₲" },
  { code: "QAR", name: "Qatari Riyal", decimals: 2, symbol: "QR" },
  { code: "RON", name: "Romanian Leu", decimals: 2, symbol: "lei" },
  { code: "RSD", name: "Serbian Dinar", decimals: 2, symbol: "din" },
  { code: "RUB", name: "Russian Ruble", decimals: 2, symbol: "₽" },
  { code: "RWF", name: "Rwandan Franc", decimals: 0, symbol: "Fr" },
  { code: "SAR", name: "Saudi Riyal", decimals: 2, symbol: "SR" },
  { code: "SBD", name: "Solomon Islands Dollar", decimals: 2, symbol: "SI$" },
  { code: "SCR", name: "Seychellois Rupee", decimals: 2, symbol: "Rs" },
  { code: "SDG", name: "Sudanese Pound", decimals: 2, symbol: "ج.س." },
  { code: "SEK", name: "Swedish Krona", decimals: 2, symbol: "kr" },
  { code: "SGD", name: "Singapore Dollar", decimals: 2, symbol: "S$" },
  { code: "SHP", name: "Saint Helena Pound", decimals: 2, symbol: "£" },
  { code: "SLE", name: "Sierra Leonean Leone", decimals: 2, symbol: "Le" },
  { code: "SOS", name: "Somali Shilling", decimals: 2, symbol: "Sh" },
  { code: "SRD", name: "Surinamese Dollar", decimals: 2, symbol: "Sr$" },
  { code: "SSP", name: "South Sudanese Pound", decimals: 2, symbol: "£" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", decimals: 2, symbol: "Db" },
  { code: "SVC", name: "Salvadoran Colón", decimals: 2, symbol: "₡" },
  { code: "SYP", name: "Syrian Pound", decimals: 2, symbol: "£" },
  { code: "SZL", name: "Swazi Lilangeni", decimals: 2, symbol: "L" },
  { code: "THB", name: "Thai Baht", decimals: 2, symbol: "฿" },
  { code: "TJS", name: "Tajikistani Somoni", decimals: 2, symbol: "SM" },
  { code: "TMT", name: "Turkmenistani Manat", decimals: 2, symbol: "T" },
  { code: "TND", name: "Tunisian Dinar", decimals: 3, symbol: "DT" },
  { code: "TOP", name: "Tongan Paʻanga", decimals: 2, symbol: "T$" },
  { code: "TRY", name: "Turkish Lira", decimals: 2, symbol: "₺" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", decimals: 2, symbol: "TT$" },
  { code: "TWD", name: "New Taiwan Dollar", decimals: 2, symbol: "NT$" },
  { code: "TZS", name: "Tanzanian Shilling", decimals: 2, symbol: "Sh" },
  { code: "UAH", name: "Ukrainian Hryvnia", decimals: 2, symbol: "₴" },
  { code: "UGX", name: "Ugandan Shilling", decimals: 0, symbol: "Sh" },
  { code: "USD", name: "United States Dollar", decimals: 2, symbol: "$" },
  { code: "USN", name: "United States Dollar (Next day)", decimals: 2, symbol: "USN" },
  {
    code: "UYI",
    name: "Uruguay Peso en Unidades Indexadas (URUIURUI)",
    decimals: 0,
    symbol: "UYI",
  },
  { code: "UYU", name: "Uruguayan Peso", decimals: 2, symbol: "$U" },
  { code: "UYW", name: "Unidad Previsional", decimals: 4, symbol: "UYW" },
  { code: "UZS", name: "Uzbekistani Som", decimals: 2, symbol: "лв" },
  { code: "VED", name: "Venezuelan Digital Bolívar", decimals: 2, symbol: "Bs.D" },
  { code: "VES", name: "Venezuelan Bolívar Soberano", decimals: 2, symbol: "Bs.S" },
  { code: "VND", name: "Vietnamese Đồng", decimals: 0, symbol: "₫" },
  { code: "VUV", name: "Vanuatu Vatu", decimals: 0, symbol: "Vt" },
  { code: "WST", name: "Samoan Tālā", decimals: 2, symbol: "T" },
  { code: "XAF", name: "Central African CFA Franc", decimals: 0, symbol: "Fr" },
  { code: "XAG", name: "Silver (one troy ounce)", decimals: 0, symbol: "XAG" },
  { code: "XAU", name: "Gold (one troy ounce)", decimals: 0, symbol: "XAU" },
  { code: "XBA", name: "European Composite Unit (EURCO)", decimals: 0, symbol: "XBA" },
  { code: "XBB", name: "European Monetary Unit (E.M.U.-6)", decimals: 0, symbol: "XBB" },
  { code: "XBC", name: "European Unit of Account 9 (E.U.A.-9)", decimals: 0, symbol: "XBC" },
  { code: "XBD", name: "European Unit of Account 17 (E.U.A.-17)", decimals: 0, symbol: "XBD" },
  { code: "XCD", name: "East Caribbean Dollar", decimals: 2, symbol: "EC$" },
  { code: "XDR", name: "Special Drawing Rights", decimals: 0, symbol: "SDR" },
  { code: "XOF", name: "West African CFA Franc", decimals: 0, symbol: "Fr" },
  { code: "XPD", name: "Palladium (one troy ounce)", decimals: 0, symbol: "XPD" },
  { code: "XPF", name: "CFP Franc", decimals: 0, symbol: "Fr" },
  { code: "XPT", name: "Platinum (one troy ounce)", decimals: 0, symbol: "XPT" },
  { code: "XSU", name: "Sucre", decimals: 0, symbol: "XSU" },
  { code: "XTS", name: "Reserved for testing purposes", decimals: 0, symbol: "XTS" },
  { code: "XUA", name: "ADB Unit of Account", decimals: 0, symbol: "XUA" },
  { code: "XXX", name: "No currency", decimals: 0, symbol: "XXX" },
  { code: "YER", name: "Yemeni Rial", decimals: 2, symbol: "﷼" },
  { code: "ZAR", name: "South African Rand", decimals: 2, symbol: "R" },
  { code: "ZMW", name: "Zambian Kwacha", decimals: 2, symbol: "ZK" },
  { code: "ZWL", name: "Zimbabwean Dollar", decimals: 2, symbol: "Z$" },
] as const

/** O(1) membership check set — built once at module load (research.md R3). */
export const CURRENCY_CODES: ReadonlySet<string> = new Set(CURRENCIES.map((c) => c.code))

/** Look up a currency record by its ISO 4217 code (must be uppercase). Returns undefined for unknown/obsolete codes. */
export function getCurrency(code: string): Currency | undefined {
  return CURRENCIES.find((c) => c.code === code)
}

/** Type guard: narrows a string to a valid ISO 4217 code in the allow-list (FR-005). */
export function isCurrencyCode(code: string): code is string {
  return CURRENCY_CODES.has(code)
}
